AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.

  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: isbn
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  GetItemHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.lambda.GetItemHandler::handleRequest
      Timeout: 30
      MemorySize: 256
      CodeUri: .
      Environment:
        Variables:
          TABLE: !Ref DynamoDbTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDbTable
      FunctionUrlConfig:
        AuthType: NONE

  PutItemHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.lambda.PutItemHandler::handleRequest
      Timeout: 30
      MemorySize: 256
      CodeUri: .
      Environment:
        Variables:
          TABLE: !Ref DynamoDbTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDbTable
      FunctionUrlConfig:
        AuthType: NONE

  UpdateItemHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.lambda.UpdateItemHandler::handleRequest
      Timeout: 30
      MemorySize: 256
      CodeUri: .
      Environment:
        Variables:
          TABLE: !Ref DynamoDbTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDbTable
      FunctionUrlConfig:
        AuthType: NONE

  DeleteItemHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.lambda.DeleteItemHandler::handleRequest
      Timeout: 30
      MemorySize: 256
      CodeUri: .
      Environment:
        Variables:
          TABLE: !Ref DynamoDbTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:DeleteItem
              Resource: {
                "Fn::Sub": [
                  "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}",
                  {
                    "tableName": {
                      "Ref": "DynamoDbTable"
                    }
                  }
                ]
              }
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  GetItemHandlerUrl:
    Description: "The Lambda Function invocation URL for GetItemHandler"
    Value: !GetAtt GetItemHandlerUrl.FunctionUrl
  PutItemHandlerUrl:
    Description: "The Lambda Function invocation URL for PutItemHandler"
    Value: !GetAtt PutItemHandlerUrl.FunctionUrl
  UpdateItemHandlerUrl:
    Description: "The Lambda Function invocation URL for UpdateItemHandler"
    Value: !GetAtt UpdateItemHandlerUrl.FunctionUrl
  DeleteItemHandlerUrl:
    Description: "The Lambda Function invocation URL for DeleteItemHandler"
    Value: !GetAtt DeleteItemHandlerUrl.FunctionUrl