AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.

  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: isbn
        Type: String

  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.lambda.GetItemHandler::handleRequest
      Timeout: 30
      MemorySize: 256
      CodeUri: .
      Environment:
        Variables:
          TABLE: !Ref DynamoDbTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDbTable
      FunctionUrlConfig:
        AuthType: NONE

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.home.amazon.serverless.lambda.PutItemHandler::handleRequest
      Timeout: 30
      MemorySize: 256
      CodeUri: .
      Environment:
        Variables:
          TABLE: !Ref BooksTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref BooksTable
      FunctionUrlConfig:
        AuthType: NONE
